# Pre-commit hook configuration file
#
# This contains the list of hooks to be run before committing code.
# Other hooks maybe added or removed as needed to suit individual project requirements.

repos:
  - repo: https://github.com/ministryofjustice/devsecops-hooks
    rev: v1.4.1
    hooks:
      - id: baseline
        env:
          GITLEAKS_CONFIGURATION_FILE: ./.gitleaks/config.toml
          GITLEAKS_IGNORE_FILE: ./.gitleaks/.gitleaksignore
