---
# Per environment values which override defaults in hmpps-digital-canteen-ui/values.yaml

generic-service:
  replicaCount: 1

  ingress:
    host: digital-canteen-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://digital-canteen-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    LAUNCHPAD_AUTH_URL: "https://launchpad-auth.hmpps.service.justice.gov.uk"
    LAUNCHPAD_URL: "https://launchpad-home.hmpps.service.justice.gov.uk"
    PRISONER_APPS_URL: "https://prisoner-apps.hmpps.service.justice.gov.uk/"
    DIGITAL_CANTEEN_API_URL: "https://digital-canteen.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PROD
    SHUTTER_ENABLED: "true"
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-digital-canteen-prod
