---
# Per environment values which override defaults in hmpps-digital-canteen-ui/values.yaml

generic-service:
  replicaCount: 1

  ingress:
    host: digital-canteen-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://digital-canteen-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    PRISONER_APPS_URL: 'https://prisoner-apps.hmpps.service.justice.gov.uk/'
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-digital-canteen-prod
